# Makefile for TZ1090-specific clocks
obj-y		+= clk.o

obj-y		+= clk-tz1090-deleter.o
obj-y		+= clk-tz1090-divider.o
obj-y		+= clk-tz1090-gate-bank.o
obj-y		+= clk-tz1090-mux-bank.o
obj-y		+= clk-tz1090-pll.o

obj-y		+= clk-tz1090-pdc.o
obj-y		+= clk-tz1090-top.o
